### ISSUE TITLE
en_US.lang missing

### ISSUE THREAD

**Issue by PCobald** [Darkhax-Minecraft/Game-Stages#10]
Please rename the folder "assets\gamestage" to "assets\gamestages".

[assets.zip](https://github.com/Darkhax-Minecraft/Game-Stages/files/1863715/assets.zip)

**Comment by darkhax** [comment]
Thanks for the request, this is fixed in https://github.com/Darkhax-Minecraft/Game-Stages/commit/e4d260c90d0244f2e29537caaddfe2d06e160391

**Comment by PCobald** [comment]
thanks
