### ISSUE TITLE
[Suggestion] JEI tie in for the various stages items

### ISSUE THREAD

**Issue by greenking13** [Darkhax-Minecraft/Game-Stages#13]
Sorry if this isn't the best place to add this, but I was wondering if it would be possible to try and create a tie into JEI such that you can do something like ">stage_one" and it would show all the items within that stage, if you've unlocked it. (I am basically asking this so that in the SevTech ages pack, it would be more readily apparent what's been unlocked by the later ages.)

Have a great day,

Greenking13

**Comment by darkhax** [comment]
I've asked Mezz about this a while ago, and he told me there is no way to add custom filtering using the current JEI API. The best that can be done is hitting f3+h to show advanced tooltips, and then enabling tooltip searching in JEI. ItemStages will include the item's stage in the tooltip.

**Comment by PCobald** [comment]
Set up options:

1. options.txt => advancedItemTooltips:true
2. NEI client.cfg => line 8 = true
3. JEI jei.cfg => lines 54; 59 and 70 = true

on Server jei is better => lines 54 and 59 = false

hope can help
