### ISSUE TITLE
About repost

### ISSUE THREAD

**Issue by forestbat** [Darkhax-Minecraft/Game-Stages#16]
Hi Dear Darkhax，I'm a carrier and translator in mcbbs of China，we think your mods（GameStages and its addons）are important for us but we have trouble to download it from curse，so I want to carry it to mcbbs，and we will recommend the author is you and let other people download from curse first，do you agree？Hope your reply。

**Comment by darkhax** [comment]
Hello, 

I get this request a lot, and I am a bit nervous to say one way or the other with it. I don't want to give any specific person special permissions which may lead to issues later down the road. My mods are licensed under LGPL 2.1 which means you should already have the permissions you need under that license. 

The main things I require with that license are
- Including original copyright/attribution 
- State any changes to the file that you make, if any.
- Include the original, or link to a place where it can be found.
- Link back to the original source code. 

I also ask that anyone distributing my mods does not do it commercially. Including advertisements or other sponsorship.

**Comment by forestbat** [comment]
Yes I know。
