### ISSUE TITLE
1.0.68 crashing server

### ISSUE THREAD

**Issue by Thyriel** [Darkhax-Minecraft/Game-Stages#2]
https://pastebin.com/WDf3aneF

Forge: 14.23.0.2512
Game Stages: 1.0.68
Bookshelf: 2.2.467
MC: 1.12.2

edit: 1.0.65 the same. Last working version 1.0.63 (i did not try the alpha versions between)

**Comment by darkhax** [comment]
Thanks for reporting the issue. The latest release should fix this. Give Curse a few minutes to review the upload. [download](https://minecraft.curseforge.com/projects/game-stages/files/2492868)

**Comment by darkhax** [comment]
https://github.com/Darkhax-Minecraft/Game-Stages/commit/022cdf55db2ea1ca7d3a8b935326fc6682d5d7aa
