### ISSUE TITLE
[Suggestion] Serene Seasons Plugin

### ISSUE THREAD

**Issue by Maxiride** [Darkhax-Minecraft/Game-Stages#20]
I'm cross-referencing this as it _might_ be of interest for both parties.

Adding a Serene Season compatibility (when also Tough as Nails is present) would enhance the modpack creation ecosystem with Quests\Adventures\Whatever to lock the player into a specific season (be it winter for instance) for improved (Hardcore)Questing.

https://github.com/Glitchfiend/SereneSeasons/issues/53

**Comment by darkhax** [comment]
This would definetly be a cool idea, however GameStages requires that features be player specific. I think seasons are done on a global basis so it's not a good fit. Perhaps they could add a command to set the season instead.

**Comment by Maxiride** [comment]
`seasons are done on a global basis` yeah that's true, I assumed for granted that I was referring to a singleplayer (or multiplayer with 1 team) instance.

**Comment by darkhax** [comment]
Yes, and in those situations where it is a global flag, there is no value to tieing in to GameStages for global flags.
