### ISSUE TITLE
Crash when starting the game

### ISSUE THREAD

**Issue by CobaltRealm** [Darkhax-Minecraft/Game-Stages#24]
https://pastebin.com/hFLE7giY

**Comment by darkhax** [comment]
Please make sure you're using the latest versions before making a report. You need to update basically every gamestage addon you have installed. 2.0 of GameStages restructures how stages are done internally and will not work with older versions of the addons. The general rule of thumb for my stage addons is that 2.x.x goes with 2.x.x and 1.x.x goes with 1.x.x.

**Comment by CobaltRealm** [comment]
I'm sorry for that, I didn't realise I had to update all the mods. I've updated all the GameStages mods to 2.0, the game starts perfectly but now when I enter a world it crashes my game

Crash Report:
https://pastebin.com/pKNsiw9v

Log:
https://pastebin.com/Memb2R8t

**Comment by darkhax** [comment]
So this one is an issue with Bookshelf not being updated.

**Comment by CobaltRealm** [comment]
Okay, thanks
