### ISSUE TITLE
Issues with AE2 autocrafting

### ISSUE THREAD

**Issue by JJSax** [Darkhax-Minecraft/Game-Stages#25]
I had updated Modern skyblock 3 and from 3.4.1.2 to 3.4.1.4 and the items that had originally been locked were unable to be crafted through AE2, though I could manually craft them.  Uninstalled this mod, and despite now having to wait a ridiculously long time for my world to load, I was able to craft everything.

**Comment by darkhax** [comment]
This mod has nothing to do with crafting. You're probably thinking of Recipe Stages.

**Comment by kylev** [comment]
See EmosewaPixel/Modern-Skyblock-3#636
