### ISSUE TITLE
[Suggestion]Unlock stage as a reward in advancement

### ISSUE THREAD

**Issue by Pabilo8** [Darkhax-Minecraft/Game-Stages#28]
It would be a faster and better way to do that than creating functions in every save directory which just run one command giving a player the next stage.
It could look like this:

` "rewards" : {
	  "unlock_stage":"stage_name"
	  }`

**Comment by darkhax** [comment]
I will look into adding this, however SevTech has already managed to do this.

**Comment by RobinNightWing** [comment]
you can use a function to run a command that unlocks a game stage

**Comment by Darkhax** [comment]
It looks like advancements are hard coded to only allow exp, loot, recipes, and functions as rewards. I would recommend using the function reward type and running commands from the mod instead. This is how modpacks like SevTech Ages have accomplished stages as rewards for advancements.
