### ISSUE TITLE
for loop not working correctly

### ISSUE THREAD

**Issue by TheFirstMinecrafter** [Darkhax-Minecraft/Game-Stages#29]
I wrote [this](https://pastebin.com/GKpYu8SJ) code., and in the chat it says 
```
ERROR: stages\knowledge(2).zs:35 > No iterator with 1 variables
ERROR: stages\knowledge(2).zs:35 > No iterator with 1 variables
ERROR: stages\knowledge(2).zs:35 > No iterator with 1 variables
```
I read the docs, and I don't have any errors as I can see. Can you help me please?

**Comment by darkhax** [comment]
This would be a better question for the CraftTweaker devs. You can ask them [here](https://discord.gg/CfFTQF3).
