### ISSUE TITLE
[Suggestion] Add a way to add/remove stages for offline players.

### ISSUE THREAD

**Issue by SuperKael** [Darkhax-Minecraft/Game-Stages#30]
I am managing a custom modpack for me and a group of my friends on a dedicated server that I am hosting. The way I have it set up, all of us should always have the same stages. However, since there is no way to manipulate the stages of offline players, this raises a problem. I am already using the command to progress through the stages anyway, so if you could add some way to give offline players stages by command, that would be great.

**Comment by darkhax** [comment]
Thanks for the request, I will look into implementing this. I can't give an ETA or guarantee that this will be fixed, but I will add it to my list.

**Comment by HenryLoenwind** [comment]
I had a quick look, thinking about allowing our recipes being tagged with a stage. However, as they all are processed in machines that also run when their owners are offline...

Also, we generally only have `GameProfile`s (and `UUID`s), not `EntityPlayer`s, as owner data.

**Comment by darkhax** [comment]
@HenryLoenwind The player data is mapped to UUID so you can get the data without the player entity ref, although being able to access data of offline players would give you the missing piece. I don't have an ETA on this feature but I would like to have it implemented before the end of the year.

**Comment by codetaylor** [comment]
@SuperKael I ran across this mod [Together Forever](https://minecraft.curseforge.com/projects/together-forever). I haven't used it, I don't know how it works, and I cannot endorse it, but it may help solve the problem. Just throwing it out there. :)

**Comment by Darkhax** [comment]
Unfortunately I don't think offline access is in the cards for now.
