### ISSUE TITLE
[Suggestion] Please Create A Tutorial

### ISSUE THREAD

**Issue by Elspar2** [Darkhax-Minecraft/Game-Stages#32]
Please create a tutorial on how to work the gamestages mod. Or update some info on the crafttweaker site. I cannot find any tutorial anywhere.

**Comment by darkhax** [comment]
I am planning to create a written tutorial series and a video based one to show off the suite of GameStage mods. These take a lot of time and work to put together though, so it may take a little while.

**Comment by darkhax** [comment]
I've updated the [README](https://github.com/Darkhax-Minecraft/Game-Stages/blob/master/README.md) of this project to contain some in depth information about how this project can be used in ModPacks, Servers, and Mods.
