### ISSUE TITLE
JEI Category GameStages Support

### ISSUE THREAD

**Issue by NillerMedDild** [Darkhax-Minecraft/Game-Stages#36]
## Feature request description
I'd like to request GameStages compatibility for the CraftTweaker function `mods.jei.JEI.hideCategory(string category)`, in order to hide tabs that the player doesn't have access to, until the appropriate GameStage.
I imagine it would work like hideCategory, but with an addition string like so:

`mods.jei.JEI.hideCategory(string stage, string category);`

## Feature request reason
- This feature would most likely reduce player confusion in the early game for my upcoming pack, aswell as reduce the time players need to spend searching through JEI.

## Feature request dependencies
- JEI

**Comment by darkhax** [comment]
This should be possible to add, however I have a feeling that JEI may cache things in a way that prevents hidden categories from being modified during runtime. I will do some tests and write back with additional information once I work things out.

**Comment by darkhax** [comment]
This feature has been added to ItemStages in this commit. https://github.com/Darkhax-Minecraft/ItemStages/commit/a00820ec3ae60ca798363d56f3bfe86a742cc124

**Comment by darkhax** [comment]
Just wanted to add, you need to know the category ID to hide the category. I don't know if JEI will give you this information anywhere, so I added the `/gamestage jeicategories` command which will print out every category in the mod.

**Comment by NillerMedDild** [comment]
Thank you very much :D 
CraftTweaker also adds `/ct jeicategories` iirc.

**Comment by JoBanJo** [comment]
Was this feature removed from version 15.0.1?
