### ISSUE TITLE
issue using hasGamestage in zenscript

### ISSUE THREAD

**Issue by Saereth** [Darkhax-Minecraft/Game-Stages#37]
I'm try to run this zenscript with gamestages installed

```
import crafttweaker.player.IPlayer;
import crafttweaker.events.IEventManager;
import crafttweaker.event.PlayerChangedDimensionEvent;

events.onPlayerChangedDimension(function(event as crafttweaker.event.PlayerChangedDimensionEvent){

	if (!event.player.hasGameStage("one")){
	//do something
	}
	return;
});
```
`

crafttweaker reports correct syntax but when the game loads it errors out in the logs and does not work and crafttweaker throws this error:
https://hastebin.com/mevabicihu.pl

I'm wasnt sure if this was a CT issue or gamestage issue (or plain old user error) so Im submitting to both  gits. (https://github.com/CraftTweaker/CraftTweaker/issues/700)

- Minecraft: 1.12.2
- Forge: 14.23.5.2782
- Crafttweaker: 4.1.13

**Comment by darkhax** [comment]
This seems to be a user error. The syntax is correct however the logic isn't. Does your script run fine if you remove the hasGameStage code?

**Comment by Saereth** [comment]
yes without the hasGameStage code it doesnt error

**Comment by Saereth** [comment]
kindlich helped me track down the logic errors, all good now!
