### ISSUE TITLE
This is VEXATING ME!!!

### ISSUE THREAD

**Issue by Furious1964** [Darkhax-Minecraft/Game-Stages#39]
Can SOMEONE explain to me what the bloody hell is Game Stages and HOW to see how I can unlock them?!?! Playing Skyfactory 4.

**Comment by Darkhax** [comment]
A game stage is a progression system in a modpack. The pack gives them to you when you complete quests, advancements, prestige rewards, loot bags, and many other things. Sky Factory 4 gives them out as prestige rewards.
