### ISSUE TITLE
[Feature Request] Expose GameStages on IPlayer

### ISSUE THREAD

**Issue by justinrusso** [Darkhax-Minecraft/Game-Stages#4]
Hello!

I would love if there was a way to check the gamestages a player has. The purpose would be so that in an advanced recipe using recipe functions, I can do something like a `.contains` to check if the player has a certain stage, and adjust the output based on that information.

Thank you!

**Comment by darkhax** [comment]
Hello, thank you for your request. What is IPlayer? It doesn't seem to appear in the Minecraft or Forge codebase.

**Comment by darkhax** [comment]
Just spoke with the craft tweaker dev about this. Definitely something I can add.

**Comment by darkhax** [comment]
Okay, I think I did this correctly. This should add 

- hasGameStage(String stage) which checks if they have a stage.
- hasAnyGameStages(String... stages) which checks if they have at least one of the stages.
- hasAllGameStages(String... stages) which checks if they have all the stages.
- addHameStage(String stage) which gives them a stage.
- removeGameStage(String stage) which removes the stage. 

I would really appreciate it if you could thoroughly test these additions and let me know how they go.

**Comment by justinrusso** [comment]
`hasAnyGameStages(String... stages)` would be something like `hasAnyGameStages("one", "two", "three");`?

Does this need the IPlayer passed in as well?

**Comment by darkhax** [comment]
Yep
