### ISSUE TITLE
[Suggestion] Ability to add new stages to players based on if they have an item in their inventory/break specific blocks

### ISSUE THREAD

**Issue by UnlimatedStone9** [Darkhax-Minecraft/Game-Stages#41]
It's as simple as that

Having the ability to add new stages to players based on if they have an item in their inventory/break specific blocks would be incredibly useful

**Comment by Darkhax** [comment]
Thanks for the feature request. This can already be done using mods like CraftTweaker with their scripts. I can see the benefit of writing another mod which adds utilities for modpack makers like this to make the job easier, but ultimately this feature doesn't belong in the base library.

**Comment by UnlimatedStone9** [comment]
That was the exact reason I came to here for the request, I'm fine if you don't do it but could you point me to an alternative.

The reason I didn't use CraftTweaker for such a feature is because I couldn't, there are no CraftTweaker methods for detecting a player breaking a block, nor possessing an item, which doesn't allow me to hook into GameStages.

Now it is technically possible to use Triumph but that has the disadvantage of displaying every minor stage as an advancement.

Nevertheless, thanks for the response!
