### ISSUE TITLE
Trying to add GameStages as a soft dependency in IntelliJ

### ISSUE THREAD

**Issue by stepsword** [Darkhax-Minecraft/Game-Stages#42]
Hi, 

Sorry this question is a bit off topic from your mod and is really a project setup issue, but I was hoping you would know.

I was recently requested to add GameStages integration to my mod - I followed the 1.12.2 instructions on your github to get it to compile GameStages. When I run Debug mode though through the IDE, it gives me a message that bookshelf is a required dependency. Is there any way to run debug mode without GameStages loading at all? I'd like to debug functionality for the mod without GameStages installed and do debugging with GameStages installed separately.

**Comment by Darkhax** [comment]
You could (and probably should) add bookshelf to your dev environment as well. It doesn't use ASM or reflection hack things so it's a relatively safe addition. You can also make your own run config which does not include the mod in the run dependency.
