### ISSUE TITLE
Game Stages cause JEI desyncs

### ISSUE THREAD

**Issue by twothe** [Darkhax-Minecraft/Game-Stages#45]
Using GameStages 1.12.2-v1.2.1 with JEI 4.15.0.291 on Forge 14.23.5.2847.

When using Game Stages serious, consistent JEI desyncs can occur. 

In detail: if I hit the + button on JEI to auto-insert items into any crafting grid they are inserted only on the server but not on the client, which not only makes further crafting impossible until the GUI is closed, but also causes heavy inventory desync issues. Sometimes just looking up a recipe (so without hitting +) is causing a desync and makes the crafting table unusable until the GUI is closed. I can't see a pattern here, but the issues happen very consistently, rendering JEI unusable.

This happens in singleplayer and LAN games. Switching between that sometimes cures the desync for a while.

Note: https://github.com/mezz/JustEnoughItems/issues/1808

**Comment by Darkhax** [comment]
This project doesn't touch JEI at all. Unless you're using the Item Stages addon.

**Comment by twothe** [comment]
Which I do. Thank you, I will forward that to ItemStages.
