### ISSUE TITLE
computercraft turtle and buildcraft fakeplayer problem

### ISSUE THREAD

**Issue by Marekone** [Darkhax-Minecraft/Game-Stages#47]
To make the computercraft/cc: tweaked turtle do anything like breaking blocks, I asked the Dev of cc: tweaked for the fakeplayer ID. I gave [ComputerCraft] all Stages but its still not able to break any blocks. Same Problem with buildcraft quarrys. At startup the logs tell me that all stages has been loaded for [ComputerCraft]. So any clue what I am doing wrong or is this a bug? If you need more info, let me know and I'll post it here.

This is what my _gameStagesFakePlayerData.json_ looks like:

> [
>     {
>         "fakePlayerName" : "rftools_builder",
>         "stages": [ "zero", "one", "two", "three", "four", "five" ]
>     },
>     {
>         "fakePlayerName" : "rftools_elevator",
>         "stages": [ "zero", "one", "two", "three", "four", "five" ]
>     },
>     {
>         "fakePlayerName": "[IF]",
>         "stages": [ "zero", "one", "two", "three", "four", "five" ]
>     },
> 	    {
>         "fakePlayerName": "[ComputerCraft]",
>         "stages": [ "zero", "one", "two", "three", "four", "five" ]
>     },
> 		{
>         "fakePlayerName": "[Buildcraft]",
>         "stages": [ "zero", "one", "two", "three", "four", "five" ]
>     },
> 	    {
>         "fakePlayerName": "[Mekanism]",
>         "stages": [ "zero", "one", "two", "three", "four", "five" ]
>     },
>     {
>         "fakePlayerName": "[Minecraft]",
>         "stages": [ "zero", "one", "two", "three", "four", "five" ]
>     },
>     {
>         "fakePlayerName": "[Modular Routers]",
>         "stages": [ "zero", "one", "two", "three", "four", "five" ]
>     }
>   ]

**Comment by Darkhax** [comment]
The name is `ComputerCraft` not `[ComputerCraft]`. https://github.com/dan200/ComputerCraft/blob/914df8b0c7cc28451ea56a53808024511ff52642/src/main/java/dan200/computercraft/shared/turtle/core/TurtlePlayer.java#L29

**Comment by Marekone** [comment]
I should have mentioned before that I tried `ComputerCraft` as an alternative and it still didn't work.
I have the same problem with Buildcraft and I tried both spellings (`Buildcraft` and `[Buildcraft]`). The Quarry from Buildcraft can't destroy blocks either.
