### ISSUE TITLE
Server players lose their gamestages after log out

### ISSUE THREAD

**Issue by RisingInIris2017** [Darkhax-Minecraft/Game-Stages#49]
#### Mod version:
GameStages-1.12.2-2.0.115

#### Forge version:

14.23.5.2847

#### Singleplayer or Multiplayer:

Multiplayer, using [Mohist](https://github.com/Mohist-Community/Mohist)

#### Installed mods:
https://paste.ubuntu.com/p/KHd4wGjgjS/

## Link to full log
This is the latest.log generated by the server.
[latest.log](https://github.com/Darkhax-Minecraft/Game-Stages/files/4485714/latest.log)
You may focus on the user whose ID is `Gastant`, he has lost 1 stage for many times in this log.

## Description of the problem
Every time a player logs out, he or she will find his gamestages are lost when he/she log in later.

I hope you could give me some help with this issue.
Is this issue related to the Minecraft server software I used?
Is GameStage mod working properly on other server software?
Thanks for your kind help in advance!

**Comment by Darkhax** [comment]
I don't provide any support or do any testing for non-official forge builds. The mod works fine with normal forge and has been heavily tested on servers without having this issue come up.

Additionally, the UUID used by Gastant in the logs is `6dcf845e-c9d6-392f-b36a-d4a5096762ca`. This is a V3 UUID indicating that they are using an offline account or that the server is running in offline mode. GameStages uses the UUID of the player to store their stages so offline accounts are not supported.
