### ISSUE TITLE
[1.12.2] Console spam "[gamestages]: Saved 0 stages for 1aaron5."

### ISSUE THREAD

**Issue by aaronhowser1** [Darkhax-Minecraft/Game-Stages#52]
![image](https://user-images.githubusercontent.com/15698722/85902050-b36f9d00-b7c8-11ea-8583-bf2dcc4f64fb.png)

Using GameStages-1.12.2-2.0.123

**Comment by Darkhax** [comment]
There is a config to turn this off, however it's not spam. This happens every time MC saves your player data and without this info some server admins get really confused.
