### ISSUE TITLE
[1.16.1] Crash with Forge 32.0.69

### ISSUE THREAD

**Issue by NielsPilgaard** [Darkhax-Minecraft/Game-Stages#53]
Hi! `GameStages-1.16.1-3.1.7` crashes with Forge 32.0.69. I believe there were some breaking changes to commands right around that update.

Crash: https://gist.github.com/NillerMedDild/e7943630bde1b96e6fcc1eb806ec37ff

**Comment by Darkhax** [comment]
Thanks, should be fixed now.
