### ISSUE TITLE
[1.16.3] Game crashes with any Forge version

### ISSUE THREAD

**Issue by Excederus** [Darkhax-Minecraft/Game-Stages#54]
Tried on Forge 34.0.9 - 34.1.0
Crashes on all tested versions. Doesn't matter if it's the only mod or when running 45 other mods. (thrown exception is the same)

[latest.log](https://github.com/Darkhax-Minecraft/Game-Stages/files/5278968/latest.log)

**Comment by Darkhax** [comment]
This log error is saying you don't have Bookshelf installed. It's listed as a dependency on the Curse page.
