### ISSUE TITLE
[1.12.2] Anvil rename can familiarise an unfamiliar item 

### ISSUE THREAD

**Issue by TheFlash787** [Darkhax-Minecraft/Game-Stages#55]
**Mod Version:** GameStages-1.12.2-2.0.123.jar

Hey!

It seems that if you put an unfamiliar item inside of an anvil (if you are either given an unfamiliar item, or received one in any way), and change the name of the item, it'll output a brand new fresh item which can be used without any issue.

Is this intended?
Thanks!
![image](https://user-images.githubusercontent.com/25883284/95671229-31935c00-0b8c-11eb-9a13-df1b988e62ed.png)
![image](https://media.discordapp.net/attachments/547962888644460545/764720215639851028/unknown.png)

**Comment by Darkhax** [comment]
This is an ItemStages issue. It's already been reported.
