### ISSUE TITLE
Gamestage freeze/lag issue

### ISSUE THREAD

**Issue by TheNimbleNinja** [Darkhax-Minecraft/Game-Stages#57]
when i claim a gamestage my game freezes/lags very bad. i dont know wat to do to fix this. after a while when the items get loaded  the game returns to normal or it kicks me out of the single player game without a crash

**Comment by Darkhax** [comment]
This is likely an issue with the specific pack that you are playing. GameStages barely runs any code when a stage is granted. Large packs like SevTech have a lot of stuff going on which can cause lag though.

**Comment by TheNimbleNinja** [comment]
its in my custom modpack when i claim the quest that gives all the stages it freezes for a bit if all the gamestages are given at once you will crash

**Comment by Darkhax** [comment]
Can you upload the crash log file?

**Comment by TheNimbleNinja** [comment]
it crashes you out of single player i dont think i have them anymore if they did create a log
