### ISSUE TITLE
Maven Dependency Documentation Incorrect

### ISSUE THREAD

**Issue by Funwayguy** [Darkhax-Minecraft/Game-Stages#59]
Instructions for including gamestages and bookshelf dependencies have not been updated to reflect the new format in which it should be used. For example, in later versions of Minecraft, the following line:

`compile "net.darkhax.gamestages:GameStages-MCVERSION:PUT_FILE_VERSION_HERE"`

should instead be:

`compile fg.deobf("net.darkhax.gamestages:GameStages-MCVERSION:PUT_FILE_VERSION_HERE")`

otherwise the development environment crashes on run due to obfuscated mappings.

**Comment by Darkhax** [comment]
Thanks, fixed in https://github.com/Darkhax-Minecraft/Game-Stages/commit/98c1cc350daf58fadb7154d87884b44df869459e
