### ISSUE TITLE
[1.12.2] Internal Server Shutting down when joining a world.

### ISSUE THREAD

**Issue by SpatialXX** [Darkhax-Minecraft/Game-Stages#60]
Unless I have to do some specials things in the scripts files, I really don't see why I keep crashing on loading a world. 
[crash-2021-03-18_15.46.04-server.txt](https://github.com/Darkhax-Minecraft/Game-Stages/files/6164454/crash-2021-03-18_15.46.04-server.txt)

**Comment by Darkhax** [comment]
Your version of Bookshelf is severely outdated.
