### ISSUE TITLE
Stages with spaces can't be removed via commands

### ISSUE THREAD

**Issue by aaronhowser1** [Darkhax-Minecraft/Game-Stages#63]
## Environment Details
**Mod Version:** GameStages-1.16.5-7.1.6
**Game Version:** 1.16.5
**Loader Type:** Forge
**Loader Version:** 36.1.4
**Game Type:** Client

## The Issue
If a game stage has a space in the name, it can't be removed via commands

## Reproduction Steps
Use another mod (like FTB Quests) to give yourself a gamestage that has a space in the name
Try to remove it using commands

## Screenshots / Media
![image](https://user-images.githubusercontent.com/15698722/120445814-9cc5b480-c34e-11eb-953f-0bd3dd19977b.png)
![image](https://user-images.githubusercontent.com/15698722/120445942-b9fa8300-c34e-11eb-9c2c-6d71650afd30.png)

## Additional Info
**How did you download the file?**
Curseforge
**Was this downloaded as part of a modpack?**
No
**Do you have Optifine, other performance mods, or shaders?**
No

**Comment by Darkhax** [comment]
Spaces are an illegal character and are not supported in any official plugin or system.

From the wiki

> These names can be up to 64 characters long and must only contain the lowercase alphabet, 0-9, underscore (_), and colons (:).
