### ISSUE TITLE
Crash on dedicated server start

### ISSUE THREAD

**Issue by facufierro** [Darkhax-Minecraft/Game-Stages#72]
## Environment Details
**Mod Version:** 8.0.1
**Game Version:** 1.18.2
**Loader Type:** Forge
**Loader Version:** 40.1.20
**Game Type:** Server

## The Issue
I start the server with GameStages and every dependency installed (and only that) and the server can't run.
Error:
Loading errors encountered: [GameStages (gamestages) has failed to load correctly ?7java.lang.ExceptionInInitializerError: null]

## Reproduction Steps
Steps that others can use to recreate this issue.
1. Download the mod.
2. Put it in your mods folder.
3. Launch a dedicated server.
4. The mod will crash.

## Log Files

https://pastebin.com/reEcCPGi

## Screenshots / Media
![image](https://user-images.githubusercontent.com/77708145/169102950-b43a1c3d-f501-4757-adf2-8f22addedcb6.png)

## Additional Info
**How did you download the file?**
curseforge
**Was this downloaded as part of a modpack?**
no
**Do you have Optifine, other performance mods, or shaders?**
no

**Comment by Darkhax** [comment]
Thanks for the report. This should now be fixed and a new release will be available on CurseForge shortly. The link will be https://www.curseforge.com/minecraft/mc-mods/game-stages/files/3797378 once approved.
