### ISSUE TITLE
[1.19.2] Can't remove stages

### ISSUE THREAD

**Issue by vizthex123** [Darkhax-Minecraft/Game-Stages#74]
## Environment Details
**Mod Version:** 11.0.2
**Game Version:** 1.19.2
**Loader Type:** Forge
**Loader Version:** 43.1.47
**Game Type:** Both I guess, happened in single-player

## The Issue
I try to run `/gamestage remove`, but it gives me this error every time:

Also happens when trying to add a stage.
![image](https://user-images.githubusercontent.com/31721920/199642112-106359c5-ef89-4536-8dd8-5bae6c52b3de.png)

## Reproduction Steps
Steps that others can use to recreate this issue.
1. Download the mod.
2. Give yourself a stage
3. Try to remove said stage

## Log Files
[latest.log](https://github.com/Darkhax-Minecraft/Game-Stages/files/9925458/latest.log)

## Additional Info
**How did you download the file?**
CurseForge app

**Was this downloaded as part of a modpack?**
No

**Do you have Optifine, other performance mods, or shaders?**
I have Radon installed.

**Comment by Darkhax** [comment]
This is an issue with KubeJS or one of your KubeJS scripts. 

> java.lang.IllegalArgumentException: Event handler 'GameStageEvents.stageRemoved' doesn't support extra id!
	at TRANSFORMER/kubejs@1902.6.0-build.101/dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:212)
	at TRANSFORMER/kubejs@1902.6.0-build.101/dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:196)
	at TRANSFORMER/kubejs@1902.6.0-build.101/dev.latvian.mods.kubejs.integration.forge.gamestages.GameStagesIntegration.stageRemoved(GameStagesIntegration.java:43)
