### ISSUE TITLE
PlayerDataHandler.IStageData#getUnlockedStages() returns empty collection on client

### ISSUE THREAD

**Issue by codetaylor** [Darkhax-Minecraft/Game-Stages#8]
I recently updated gamestages from `1.0.76` to `1.0.78` and staged recipes stopped working in my mod, Artisan Worktables.

I narrowed the issue down to this call:
```
PlayerDataHandler.getStageData(player).getUnlockedStages()
```

On the server it returns a collection with the proper strings:
![image](https://user-images.githubusercontent.com/1240716/35841476-07231a84-0ab1-11e8-9da9-87ba89b6c2f9.png)

However, on the client:
![image](https://user-images.githubusercontent.com/1240716/35841499-1a7dacb6-0ab1-11e8-85e8-ed14d76ae941.png)

I tested in the previous version I had, `1.0.76` and everything works as expected. After updating to `1.0.78` the issue began.

Please let me know if there is anything I can do to help, thanks!

**Comment by darkhax** [comment]
Thanks for the report, and sorry for the hassle. I unintentionally broke packet syncing through a more invasive code cleanup script. Everything should be fixed with build 80.

**Comment by codetaylor** [comment]
No worries, no hassle. Bugs are part of the process. :)

Thanks for the fast turnaround on this issue and for all the work you do.
