### ISSUE TITLE
Kubejs support

### ISSUE THREAD

**Issue by Hexasphere0** [Darkhax-Minecraft/Game-Stages#80]
## Description
Right now, the only way to stage items with a script is using CraftTweaker (I could not find anything mentioning kubejs support). In my custom modpack, I am using kubejs for everything except game stages, so it would be nice to be able to do that in kubejs as well.

## Additional Context
https://www.curseforge.com/minecraft/mc-mods/kubejs

**Comment by Darkhax** [comment]
Hello, KubeJS is unsupported and I have no plans or interest in adding support for it. I've heard they added support on their end for GameStages or that there may be 3rd party addons but that is a question for them as those are not officially supported.

**Comment by RemagOfficial** [comment]
please add kubejs support, i really don't like the fact i would need to use both kubejs and crafttweaker just to use game stages because kubejs is way more user friendly and makes adding recipes and other things super simple
