### ISSUE TITLE
Game crash when teleporting to an other dimension

### ISSUE THREAD

**Issue by winnetrie83** [Darkhax-Minecraft/Game-Stages#81]
## Environment Details
**Mod Version:** GameStages-Forge-1.19.2-11.1.4
**Game Version:**MC 1.19.2
**Loader Type:** Forge
**Loader Version:** 43.2.21
**Game Type:** Client

## The Issue
Write a description of the issue here. Include as much detail as possible.
I have setup a testing environment with minimal required mods.
Wich is basically : Lobby, FTBChunks (and dependencies), Gamestages
When teleporting to another dimension with command: "/lobby, /spawn", the game crashes due to a class references that is non-existent.
The same happens when teleporting to the nether via ingame portal (no command)
I checked within ftbchunks and indeed the method "syncStages" does not exists. It should be "sync"
I'm very sure it is an issue between FTBchunks and Gamagestages, because the issue persists even without Lobby.
By removing/disabling FTBChunks or Gamestages the issue is not present.

## Reproduction Steps
Steps that others can use to recreate this issue.
1. Download the mod.
2. Put it in your mods folder.
3. Launch a dedicated server.
4. The mod will crash.

## Log Files
https://pastebin.com/veq5tbiG

## Screenshots / Media
You may include relevant media here if you have any. This can be screenshots, gifs, YouTube videos, Twitch Clips, etc.

## Additional Info
**How did you download the file?**
By using the curseforge app(overwolf)

**Was this downloaded as part of a modpack?**
No
**Do you have Optifine, other performance mods, or shaders?**
No

**Comment by Darkhax** [comment]
After looking into this issue, I think FTBChunks has broken compatibility for GameStages or they forgot to update a part of the code. The issue should be reported to them.

**Comment by desht** [comment]
Yeah, it's on FTB Chunks. Definitely not a Game Stages problem.
