### ISSUE TITLE
Broken link in curse description that came in with the legacy change

### ISSUE THREAD

**Issue by Lothrazar** [Darkhax-Minecraft/Game-Stages#82]
On the curseforge page you say 

"You can find a list of all mods that support GameStages [here.](https://minecraft.curseforge.com/projects/game-stages/relations/dependents?filter-related-dependents=3)"

But that link no longer links to what you want it to be.  

With the new legacy and non legacy sites i think the link should be this if you check it out 

https://www.curseforge.com/minecraft/mc-mods/game-stages/relations/dependents?filter-related-dependents=3

Currently it accurately forwards to the legacy site and query parameter filter is applied in the dropdown menus and search results

(any links with minecraft.curseforge.com/projects are super deprecated)

**Comment by Darkhax** [comment]
Thanks for letting me know about this, I've now updated the link. Hopefully we will have a non-legacy solution soon.
