### ISSUE TITLE
No fluids in JEI 

### ISSUE THREAD

**Issue by benbenlaw** [Darkhax-Minecraft/Game-Stages#83]
## Description
Fluids should be hidden in JEI from a mod if that mod is staged

## Additional Context
basically unless i missed something i can't hide fluids in JEI

## Screenshots / Media
![image](https://github.com/Darkhax-Minecraft/Game-Stages/assets/42780877/48a1bf02-747e-44e6-9943-ff3bc77a2b63)

**Comment by Darkhax** [comment]
This is an issue with ItemStages not GameStages. Also I am only supporting 1.19.2, 1.20.1, and 1.20.4 at this time.
