### ISSUE TITLE
Stop dropping "unknown" items?

### ISSUE THREAD

**Issue by Carnaxus** [Darkhax-Minecraft/Game-Stages#84]
I'm wondering if there's a way to make my character not drop "unknown" items.  I may not be able to use them yet but I would really love to not have things fly out of my hands.  Essentially, rather than my character going "I don't know what this is so it must be useless," I want my character to go "I don't know what this is but it might be useful later."

Yes, I'm asking this because of SevTech: Ages.

**Comment by Darkhax** [comment]
The mod that drops the items is an addon called ItemStages. If you're on 1.12.2 you can configure this behaviour using the itemstages config file in the config folder. Specifically `allowHoldingRestricted`.

**Comment by Carnaxus** [comment]
Thank you 😄
